
// This file is generated by Firebase Studio
import { NextResponse } from 'next/server';
import type { Product } from '@/lib/types';
import { publishToShopify } from '@/lib/shopify';

export async function POST(req: Request) {
  try {
    const { product, storeName } = (await req.json()) as { product: Product, storeName: string };
    
    if (!product) {
      return NextResponse.json({ error: 'Product data is required.' }, { status: 400 });
    }
    if (!storeName) {
      return NextResponse.json({ error: 'Shopify store name is required.' }, { status: 400 });
    }

    const result = await publishToShopify(product, storeName);

    return NextResponse.json({ success: true, shopifyId: result.product.id, storeName });
  } catch (error: any) {
    console.error(`Shopify publish failed for store:`, error);
    return NextResponse.json({ error: error.message || 'Failed to publish to Shopify' }, { status: 500 });
  }
}
