// This file is generated by Firebase Studio
import { NextResponse } from 'next/server';
import type { Product } from '@/lib/types';
import { publishToShopify } from '@/lib/shopify';

export async function POST(req: Request) {
  try {
    const product = (await req.json()) as Product;
    if (!product) {
      return NextResponse.json({ error: 'Product data is required.' }, { status: 400 });
    }

    const result = await publishToShopify(product);

    return NextResponse.json({ success: true, shopifyId: result.product.id });
  } catch (error: any) {
    console.error('Shopify publish failed:', error);
    return NextResponse.json({ error: error.message || 'Failed to publish to Shopify' }, { status: 500 });
  }
}
