// This file is generated by Firebase Studio
import { NextResponse } from 'next/server';
import type { Product } from '@/lib/types';
import { publishToShopify } from '@/lib/shopify';

export async function POST(req: Request) {
  try {
    const product = (await req.json()) as Product;
    if (!product) {
      return NextResponse.json({ error: 'Product data is required.' }, { status: 400 });
    }

    // Explicit check for environment variables at the start of the request.
    // This ensures that we fail fast with a clear error message if secrets are not configured.
    if (!process.env.SHOPIFY_STORE_URL || !process.env.SHOPIFY_ADMIN_ACCESS_TOKEN) {
        console.error('Shopify credentials missing from environment variables.');
        return NextResponse.json({ 
            error: 'Shopify configuration is missing on the server. Please ensure SHOPIFY_STORE_URL and SHOPIFY_ADMIN_ACCESS_TOKEN are set in your environment secrets.' 
        }, { status: 500 });
    }

    const result = await publishToShopify(product);

    return NextResponse.json({ success: true, shopifyId: result.product.id });
  } catch (error: any) {
    console.error('Shopify publish failed:', error);
    // The error from publishToShopify will now be more detailed.
    return NextResponse.json({ error: error.message || 'Failed to publish to Shopify' }, { status: 500 });
  }
}
