// This file is generated by Firebase Studio.
'use server';
/**
 * @fileOverview AI agent that suggests tags, keywords, and categories for products based on their descriptions.
 *
 * - suggestTagsKeywordsCategory - A function that suggests tags, keywords, and categories for a product description.
 * - SuggestTagsKeywordsCategoryInput - The input type for the suggestTagsKeywordsCategory function.
 * - SuggestTagsKeywordsCategoryOutput - The return type for the suggestTagsKeywordsCategory function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestTagsKeywordsCategoryInputSchema = z.object({
  description: z.string().describe('The generated product description.'),
});
export type SuggestTagsKeywordsCategoryInput = z.infer<typeof SuggestTagsKeywordsCategoryInputSchema>;

const SuggestTagsKeywordsCategoryOutputSchema = z.object({
  tags: z.array(z.string()).describe('Suggested tags for the product.'),
  keywords: z.array(z.string()).describe('Suggested keywords for the product.'),
  category: z.string().describe('Suggested category for the product.'),
});
export type SuggestTagsKeywordsCategoryOutput = z.infer<typeof SuggestTagsKeywordsCategoryOutputSchema>;

export async function suggestTagsKeywordsCategory(input: SuggestTagsKeywordsCategoryInput): Promise<SuggestTagsKeywordsCategoryOutput> {
  return suggestTagsKeywordsCategoryFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestTagsKeywordsCategoryPrompt',
  input: {schema: SuggestTagsKeywordsCategoryInputSchema},
  output: {schema: SuggestTagsKeywordsCategoryOutputSchema},
  prompt: `You are an expert in e-commerce SEO.

  Based on the following product description, suggest relevant tags, keywords, and a category for the product.

  Description: {{{description}}}

  Format your response as a JSON object with "tags", "keywords", and "category" fields.  The "tags" and "keywords" fields should be arrays of strings.
  `,
});

const suggestTagsKeywordsCategoryFlow = ai.defineFlow(
  {
    name: 'suggestTagsKeywordsCategoryFlow',
    inputSchema: SuggestTagsKeywordsCategoryInputSchema,
    outputSchema: SuggestTagsKeywordsCategoryOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
