// This file is generated by Firebase Studio

import type { Product } from './types';

// Helper to build a query string from the best available product identifiers.
// It joins all available fields to create a more specific search query.
const buildQuery = (product: Product): string => {
  return [product.ean, product.code, product.name]
    .filter(Boolean) // Remove any empty or null values
    .join(' '); // Join by space
};

export const handleExternalSearch = (product: Product, platform: 'google' | 'ebay' | 'amazon' | 'otto') => {
    const query = buildQuery(product);
    if (!query) return;

    let searchUrl = '';
    switch (platform) {
        case 'google':
            searchUrl = `https://www.google.com/search?q=${encodeURIComponent(query)}`;
            break;
        case 'ebay':
            searchUrl = `https://www.ebay.de/sch/i.html?_nkw=${encodeURIComponent(query)}`;
            break;
        case 'amazon':
            searchUrl = `https://www.amazon.de/s?k=${encodeURIComponent(query)}`;
            break;
        case 'otto':
            searchUrl = `https://www.otto.de/suche/${encodeURIComponent(query)}`;
            break;
    }
    window.open(searchUrl, '_blank', 'noopener,noreferrer');
};
