// This file is generated by Firebase Studio
import { initializeApp, getApps, getApp } from 'firebase/app';
import { getAuth } from 'firebase/auth';

const firebaseConfig = {
  apiKey: "AIzaSyBnLCLDNhL64QG6kagfwSAXyCOdB-H7ENA",
  authDomain: "listingflow-sp4tf.firebaseapp.com",
  projectId: "listingflow-sp4tf",
  storageBucket: "listingflow-sp4tf.firebasestorage.app",
  messagingSenderId: "935922706940",
  appId: "1:935922706940:web:2fc04bfc3e3240cfc82a79",
  measurementId: "G-J79SJF5H3B"
};

// Initialize Firebase
const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
const auth = getAuth(app);

export { app, auth };
