// A subset of the official Shopify Product Taxonomy.
// For a complete and up-to-date list, refer to Shopify's official documentation.

export const shopifyTaxonomy: string[] = [
  'Bekleidung & Zubehör',
  'Bekleidung & Zubehör > Kleidung',
  'Bekleidung & Zubehör > Kleidung > Anzüge',
  'Bekleidung & Zubehör > Kleidung > Anzüge > Smokings',
  'Bekleidung & Zubehör > Kleidung > Baby- & Kleinkindkleidung',
  'Bekleidung & Zubehör > Kleidung > Baby- & Kleinkindkleidung > Baby- & Kleinkind-Einteiler',
  'Bekleidung & Zubehör > Kleidung > Baby- & Kleinkindkleidung > Baby-Badehosen',
  'Bekleidung & Zubehör > Kleidung > Oberbekleidung',
  'Bekleidung & Zubehör > Kleidung > Oberbekleidung > Mäntel & Jacken',
  'Bekleidung & Zubehör > Kleidung > Oberbekleidung > Westen',
  'Bekleidung & Zubehör > Kleidung > Hosen',
  'Bekleidung & Zubehör > Kleidung > Hemden & Tops',
  'Bekleidung & Zubehör > Kleidung > Röcke',
  'Bekleidung & Zubehör > Kleidung > Sportkleidung',
  'Bekleidung & Zubehör > Kleidung > Sportkleidung > Sport-BHs',
  'Bekleidung & Zubehör > Kleidung > Sportkleidung > Sport-Trikots',
  'Bekleidung & Zubehör > Kleidung > Sportkleidung > Sporthosen',
  'Bekleidung & Zubehör > Kleidung > Unterwäsche & Socken',
  'Bekleidung & Zubehör > Kleidung > Uniformen',
  'Bekleidung & Zubehör > Schuhe',
  'Bekleidung & Zubehör > Schuhe > Sportschuhe',
  'Bekleidung & Zubehör > Schmuck',
  'Bekleidung & Zubehör > Uhren',
  'Elektronik',
  'Elektronik > Audio',
  'Elektronik > Audio > Audio-Komponenten',
  'Elektronik > Audio > Kopfhörer & Headsets',
  'Elektronik > Audio > Lautsprecher',
  'Elektronik > Audio > MP3-Player',
  'Elektronik > Kameras & Optik',
  'Elektronik > Kameras & Optik > Kameras',
  'Elektronik > Kameras & Optik > Objektive & Optik',
  'Elektronik > Computer',
  'Elektronik > Computer > Computer-Komponenten',
  'Elektronik > Computer > Laptops',
  'Elektronik > Computer > Tablets',
  'Elektronik > Videospiele & Konsolen',
  'Elektronik > Videospiele & Konsolen > Videospielkonsolen',
  'Heim & Garten',
  'Heim & Garten > Badezimmer-Zubehör',
  'Heim & Garten > Haushaltsgeräte',
  'Heim & Garten > Haushaltsgeräte > Klimaanlagen',
  'Heim & Garten > Haushaltsgeräte > Staubsauger & Bodenpflege > Staubsauger',
  'Heim & Garten > Haushaltsgeräte > Waschmaschinen & Trockner',
  'Heim & Garten > Küche & Esszimmer',
  'Heim & Garten > Küche & Esszimmer > Koch- & Backgeschirr',
  'Heim & Garten > Küche & Esszimmer > Koch- & Backgeschirr > Kochgeschirrsets',
  'Heim & Garten > Küche & Esszimmer > Küchengeräte',
  'Heim & Garten > Küche & Esszimmer > Küchengeräte > Brotbackautomaten',
  'Heim & Garten > Küche & Esszimmer > Küchengeräte > Fritteusen',
  'Heim & Garten > Küche & Esszimmer > Küchengeräte > Kaffee-, Tee- & Espressomaschinen',
  'Heim & Garten > Küche & Esszimmer > Küchengeräte > Mixer & Entsafter',
  'Heim & Garten > Küche & Esszimmer > Küchengeräte > Küchenmaschinen',
  'Heim & Garten > Küche & Esszimmer > Tischgeschirr',
  'Sportartikel',
  'Sportartikel > Mannschaftssportarten',
  'Sportartikel > Mannschaftssportarten > Basketball',
  'Sportartikel > Mannschaftssportarten > Fußball',
  'Sportartikel > Mannschaftssportarten > Volleyball',
  'Spielzeug & Spiele',
  'Spielzeug & Spiele > Puzzles',
  'Spielzeug & Spiele > Spielzeug > Action- & Spielfiguren',
  'Spielzeug & Spiele > Spielzeug > Bauspielzeug',
  'Tierbedarf',
  'Tierbedarf > Tierhaltung & Zubehör',
  'Tierbedarf > Hundebedarf',
  'Tierbedarf > Katzenbedarf',
];
