export type Product = {
  id: string;
  name: string;
  code: string;
  quantity: number;
  price: number;
  description: string;
  image: string;
  supplier: string;
  location: string;
  tags: string[];
  keywords: string[];
  category: string;
  ebayCategoryId: string;
  listingStatus: 'draft' | 'listed' | 'error' | 'new' | 'used' | 'refurbished';
  brand?: string;
  productType?: string;
  ean?: string;
  technicalSpecs?: Record<string, string>;
};
