// This file is generated by Firebase Studio
import { NextResponse } from 'next/server';
import type { Product } from '@/lib/types';
import { exportProductsToERPNext } from '@/lib/erpnext';

export async function POST(req: Request) {
  try {
    const { productsToExport } = (await req.json()) as { productsToExport: Product[] };

    if (!productsToExport || productsToExport.length === 0) {
      return NextResponse.json({ error: 'No products provided for export.' }, { status: 400 });
    }

    // This is a server context, so a dummy setLoading is fine.
    const setLoading = (_: boolean) => {};
    const { successCount, errorMessages } = await exportProductsToERPNext(setLoading, productsToExport);

    if (errorMessages.length > 0) {
      // If there are errors, even partial success is a multi-status event.
      return NextResponse.json({ 
        message: `Export partially complete. Successfully updated ${successCount}/${productsToExport.length} products.`,
        errors: errorMessages 
      }, { status: 207 }); // 207 Multi-Status
    }

    return NextResponse.json({ message: `Successfully updated ${successCount} products in ERPNext.` });

  } catch (error: any) {
    console.error('ERPNext export API route failed:', error);
    // Ensure that even unexpected errors return a JSON response
    return NextResponse.json({ error: error.message || 'Failed to export to ERPNext' }, { status: 500 });
  }
}
