// This file is generated by Firebase Studio
import { NextResponse } from 'next/server';
import type { Product } from '@/lib/types';
import { exportProductsToERPNext } from '@/lib/erpnext';

export async function POST(req: Request) {
  try {
    const { productsToExport } = (await req.json()) as { productsToExport: Product[] };

    if (!productsToExport || productsToExport.length === 0) {
      return NextResponse.json({ error: 'No products provided for export.' }, { status: 400 });
    }

    // The 'setLoading' function is a client-side state setter and cannot be used here.
    // The logic within exportProductsToERPNext that uses it needs to be adapted or removed if it's only for UI.
    // For now, we pass a dummy function.
    const setLoading = (_: boolean) => {};
    const { successCount, errorMessages } = await exportProductsToERPNext(setLoading, productsToExport);

    if (errorMessages.length > 0) {
      return NextResponse.json({ 
        message: `Export partially complete. Successfully updated ${successCount}/${productsToExport.length} products.`,
        errors: errorMessages 
      }, { status: 207 }); // 207 Multi-Status
    }

    return NextResponse.json({ success: true, message: `Successfully updated ${successCount} products in ERPNext.` });

  } catch (error: any) {
    console.error('ERPNext export API route failed:', error);
    return NextResponse.json({ error: error.message || 'Failed to export to ERPNext' }, { status: 500 });
  }
}
