// This file is generated by Firebase Studio

import { NextResponse } from "next/server";
import { findEbayCategoryId } from "@/ai/flows/find-ebay-category-id";

export async function POST(req: Request) {
  try {
    const { productName, ean } = await req.json();

    if (!productName) {
      return NextResponse.json({ error: "Product name is required" }, { status: 400 });
    }

    const result = await findEbayCategoryId({ productTitle: productName, ean });

    if (result.categoryId) {
      return NextResponse.json(result);
    } else {
      return NextResponse.json({ error: "No matching category found" }, { status: 404 });
    }
  } catch (error) {
    console.error("Failed to find eBay category:", error);
    return NextResponse.json({ error: "An internal error occurred." }, { status: 500 });
  }
}
