// This file is generated by Firebase Studio
'use client';

import * as React from 'react';
import { useAuth } from '@/contexts/auth-context';
import { useRouter, useSearchParams } from 'next/navigation';
import { Button } from '@/components/ui/button';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { useToast } from '@/hooks/use-toast';
import { Loader2 } from 'lucide-react';
import { Package } from 'lucide-react';

const MicrosoftIcon = () => (
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" className="mr-2" viewBox="0 0 16 16">
        <path d="M7.462 0H0v7.462h7.462V0zM16 0H8.538v7.462H16V0zM7.462 8.538H0V16h7.462V8.538zM16 8.538H8.538V16H16V8.538z"/>
    </svg>
)

export default function LoginPage() {
  const [isMicrosoftLoading, setIsMicrosoftLoading] = React.useState(false);
  const { user, loginWithMicrosoft } = useAuth();
  const router = useRouter();
  const searchParams = useSearchParams();
  const { toast } = useToast();

  React.useEffect(() => {
    if (user) {
      const nextUrl = searchParams.get('next') || '/';
      router.push(nextUrl);
    }
  }, [user, router, searchParams]);

  const handleMicrosoftLogin = async () => {
    setIsMicrosoftLoading(true);
    try {
        await loginWithMicrosoft();
        // The useEffect above will handle the redirect on user state change.
    } catch(error: any) {
        toast({
            variant: 'destructive',
            title: 'Microsoft Login Failed',
            description: error.message || 'Could not sign in with Microsoft. Please try again.',
        });
    } finally {
        setIsMicrosoftLoading(false);
    }
  };

  return (
    <div className="flex min-h-screen items-center justify-center bg-muted/40">
      <Card className="mx-auto max-w-sm">
        <CardHeader className="text-center">
            <div className="flex justify-center items-center mb-4">
               <Package className="h-8 w-8" />
            </div>
          <CardTitle className="text-2xl">Login to ListingFlow</CardTitle>
          <CardDescription>
            Please sign in using your company&apos;s Microsoft account to continue.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid gap-4">
            <Button variant="outline" onClick={handleMicrosoftLogin} disabled={isMicrosoftLoading}>
                {isMicrosoftLoading ? (
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                ) : (
                    <MicrosoftIcon />
                )}
                Sign in with Microsoft
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
