

// This file is generated by Firebase Studio
'use client';
import './globals.css';
import { Toaster } from "@/components/ui/toaster";
import * as React from 'react';
import { usePathname, useRouter } from 'next/navigation';
import { AppShell } from '@/components/app-shell';
import { getAuth, onAuthStateChanged } from 'firebase/auth';
import { app } from '@/lib/firebase';
import { Loader2 } from 'lucide-react';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const isAuthPage = pathname.startsWith('/login') || pathname.startsWith('/auth');
  
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <title>ListingFlow</title>
        <meta name="description" content="Streamline your e-commerce listing process." />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        ></link>
      </head>
      <body className="font-body antialiased">
        {isAuthPage ? (
          children
        ) : (
          <AppShell>
            {children}
          </AppShell>
        )}
        <Toaster />
      </body>
    </html>
  );
}
