// This file is generated by Firebase Studio
'use client';

import * as React from 'react';
import {
  File,
  PlusCircle,
  Upload,
  FilePenLine,
  Database,
} from 'lucide-react';
import Papa from 'papaparse';

import { Button } from '@/components/ui/button';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import {
    Sheet,
    SheetContent,
    SheetHeader,
    SheetTitle,
    SheetDescription,
    SheetTrigger
} from '@/components/ui/sheet';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogTrigger,
} from '@/components/ui/dialog';
import type { Product } from '@/lib/types';
import { initialProducts } from '@/lib/data';
import { ProductDataTable } from '@/components/product-data-table';
import { getColumns } from '@/components/product-columns';
import { generateProductDescription } from '@/ai/flows/generate-product-description';
import { findProductDescription } from '@/ai/flows/find-product-description';
import { useToast } from '@/hooks/use-toast';
import { ProductForm } from '@/components/product-form';
import { BulkEditForm } from '@/components/bulk-edit-form';
import { ErpDataProvider, useErpData } from '@/contexts/erp-data-context';

function DashboardClient() {
  const [products, setProducts] = React.useState<Product[]>([]);
  const [isSheetOpen, setIsSheetOpen] = React.useState(false);
  const [isBulkEditOpen, setIsBulkEditOpen] = React.useState(false);
  const [selectedProduct, setSelectedProduct] = React.useState<Product | null>(null);
  const [selectedProductIds, setSelectedProductIds] = React.useState<string[]>([]);
  const [isLoading, setIsLoading] = React.useState(true);
  const [generatingProductId, setGeneratingProductId] = React.useState<string | null>(null);
  const { toast } = useToast();
  const fileInputRef = React.useRef<HTMLInputElement>(null);
  const erpFileInputRef = React.useRef<HTMLInputElement>(null);
  const { setErpData, erpData } = useErpData();

  React.useEffect(() => {
    try {
      const storedProducts = localStorage.getItem('listingFlowProducts');
      if (storedProducts) {
        setProducts(JSON.parse(storedProducts));
      } else {
        setProducts(initialProducts);
      }
    } catch (error) {
      console.error('Failed to parse products from localStorage', error);
      setProducts(initialProducts);
    }
    setIsLoading(false);
  }, []);

  React.useEffect(() => {
    if (!isLoading) {
      localStorage.setItem('listingFlowProducts', JSON.stringify(products));
    }
  }, [products, isLoading]);

  const handleAddProduct = () => {
    setSelectedProduct(null);
    setIsSheetOpen(true);
  };

  const handleEditProduct = (product: Product) => {
    setSelectedProduct(product);
    setIsSheetOpen(true);
  };

  const handleDeleteProduct = (id: string) => {
    setProducts(products.filter((p) => p.id !== id));
  };
  
  const handleBulkDelete = (ids: string[]) => {
    setProducts(products.filter((p) => !ids.includes(p.id)));
    toast({
        title: 'Products Deleted',
        description: `${ids.length} products have been deleted successfully.`,
    });
  };

  const handleSaveProduct = (productData: Product) => {
    if (selectedProduct) {
        setProducts(products.map((p) => (p.id === productData.id ? productData : p)));
    } else {
        setProducts([
            { ...productData, id: crypto.randomUUID() },
            ...products,
        ]);
    }
    setIsSheetOpen(false);
    setSelectedProduct(null);
  };
  
  const handleUpdateProduct = (id: string, data: Partial<Product>) => {
    setProducts(products.map(p => p.id === id ? { ...p, ...data } : p));
  };

  const handleSaveBulkEdit = (data: Partial<Product>) => {
    setProducts(products.map(p => {
        if (selectedProductIds.includes(p.id)) {
            const updatedProduct = { ...p };
            for (const key in data) {
                if (data[key as keyof typeof data]) {
                    (updatedProduct as any)[key] = data[key as keyof typeof data];
                }
            }
            return updatedProduct;
        }
        return p;
    }));
    toast({
        title: 'Bulk Edit Successful',
        description: `${selectedProductIds.length} products have been updated.`,
    });
    setIsBulkEditOpen(false);
    setSelectedProductIds([]);
  };
  
  const handleGenerateDescription = async (product: Product) => {
    setGeneratingProductId(product.id);
    try {
      const result = await generateProductDescription({
        productName: product.name,
        category: product.category,
        listingStatus: product.listingStatus as 'new' | 'used' | 'refurbished',
        brand: product.brand,
      });
      
      setProducts(products.map(p => p.id === product.id ? {
        ...p,
        description: result.description,
        tags: Array.isArray(result.tags) ? result.tags : [],
        keywords: Array.isArray(result.keywords) ? result.keywords : [],
        category: result.category,
        ebayCategoryId: result.ebayCategoryId,
        brand: result.brand,
        productType: result.productType,
        ean: result.ean,
      } : p));

      toast({
        title: 'AI Magic Successful!',
        description: `Description for "${product.name}" has been generated.`,
      });

    } catch (error) {
      console.error('Failed to generate description:', error);
      toast({
        variant: 'destructive',
        title: 'AI Magic Failed',
        description: 'Could not generate a new description. Please try again.',
      });
    } finally {
      setGeneratingProductId(null);
    }
  };

  const handleCopyDescription = async (product: Product, source: 'otto' | 'ebay') => {
    setGeneratingProductId(product.id);
    try {
      const result = await findProductDescription({
        productName: product.name,
        brand: product.brand,
        ean: product.ean,
        source: source,
      });
      
      if (result.description || Object.keys(result.technicalSpecs).length > 0) {
        handleUpdateProduct(product.id, { 
          description: result.description,
          technicalSpecs: {
            ...product.technicalSpecs,
            ...result.technicalSpecs
          }
        });
        toast({
          title: 'Content Copied!',
          description: `Description and specs for "${product.name}" have been copied from ${source}.de.`,
        });
      } else {
        toast({
          variant: 'destructive',
          title: 'Copy Failed',
          description: `Could not find content for "${product.name}" on ${source}.de.`,
        });
      }

    } catch (error) {
      console.error(`Failed to copy description from ${source}:`, error);
      toast({
        variant: 'destructive',
        title: 'Copy Failed',
        description: `An error occurred while copying from ${source}.de.`,
      });
    } finally {
      setGeneratingProductId(null);
    }
  };

  const handleExportToCSV = () => {
    const headers = [
      'id', 'name', 'code', 'quantity', 'price', 'description', 
      'image', 'supplier', 'location', 'tags', 'keywords', 'category', 'ebayCategoryId', 'listingStatus'
    ];
    const rows = products.map(product => 
      headers.map(header => {
        const value = product[header as keyof Product];
        if (Array.isArray(value)) {
          return `"${value.join(', ')}"`;
        }
        if (typeof value === 'string') {
          return `"${value.replace(/"/g, '""')}"`;
        }
        return value;
      }).join(',')
    );

    const csvContent = [headers.join(','), ...rows].join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    const url = URL.createObjectURL(blob);
    link.setAttribute('href', url);
    link.setAttribute('download', `products-export-${new Date().toISOString()}.csv`);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    
    toast({
        title: 'Export Successful',
        description: 'Your products have been exported to CSV.',
    });
  };

  const handleImportClick = () => {
    fileInputRef.current?.click();
  };
  
  const handleErpImportClick = () => {
    erpFileInputRef.current?.click();
  };

  const handleCSVUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    Papa.parse(file, {
      header: true,
      skipEmptyLines: true,
      complete: (results) => {
        try {
          const newProducts = results.data.map((row: any): Product => {
            return {
              id: crypto.randomUUID(),
              name: row['Artikelname'] || 'No Name',
              code: row['Artikel-Code']?.toString() || '',
              quantity: 0,
              price: 0,
              description: '',
              image: '',
              supplier: '',
              location: '',
              tags: [],
              keywords: [],
              category: row['Artikelgruppe'] || '',
              ebayCategoryId: '',
              listingStatus: 'draft',
              brand: '',
              productType: '',
              ean: '',
              technicalSpecs: {},
            };
          }).filter(p => p.code); // Filter out any items without a SKU

          const updatedProducts = [...newProducts, ...products];
          setProducts(updatedProducts);

          toast({
            title: 'Import Successful',
            description: `${newProducts.length} products have been imported and added to the list.`,
          });
        } catch (err) {
          console.error("Error processing CSV data:", err);
          toast({
            variant: 'destructive',
            title: 'Import Failed',
            description: 'Could not process the CSV file. Please check the file format.',
          });
        }
      },
      error: (err) => {
        console.error("Error parsing CSV:", err);
        toast({
            variant: 'destructive',
            title: 'Import Failed',
            description: 'Could not parse the CSV file. Please ensure it is a valid CSV.',
        });
      },
    });
    
    if(event.target) {
        event.target.value = '';
    }
  };

  const handleErpCSVUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    Papa.parse(file, {
      header: true,
      skipEmptyLines: true,
      complete: (results) => {
        const mappedData = results.data.map(row => ({
          sku: (row as any)["Artikel-Code"]?.toString().trim() || "",
          ean: (row as any)["Artikel-Code"]?.toString().trim() || "", // Assuming EAN is same as SKU for now
          name: (row as any)["Artikelname"]?.toString().trim() || "",
          category: (row as any)["Artikelgruppe"]?.toString().trim() || "",
        }));
        setErpData(mappedData);
        toast({
          title: "ERP Data Loaded",
          description: `${mappedData.length} records are now available for autocompletion.`,
        });
      },
      error: (err) => {
        console.error("Error parsing ERP CSV:", err);
        toast({
            variant: 'destructive',
            title: 'ERP Import Failed',
            description: 'Could not parse the ERP CSV file.',
        });
      },
    });
     if(event.target) {
        event.target.value = '';
    }
  };


  const columns = React.useMemo(() => getColumns({
      onEdit: handleEditProduct,
      onDelete: handleDeleteProduct,
      onGenerate: handleGenerateDescription,
      onUpdate: handleUpdateProduct,
      onCopyDescription: handleCopyDescription,
      generatingProductId,
  }), [generatingProductId, products]);

  if (isLoading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="text-2xl">Loading Products...</div>
      </div>
    );
  }

  const selectedData = products.filter(p => selectedProductIds.includes(p.id));

  return (
    <main className="grid flex-1 items-start gap-4 p-4 sm:px-6 sm:py-0 md:gap-8">
      <Card>
        <CardHeader className="flex flex-row items-center">
          <div>
            <CardTitle>Products</CardTitle>
             <CardDescription>
              Manage your products.{' '}
              <span className="text-primary font-medium">
                {erpData.length > 0 ? `${erpData.length} ERP records loaded.` : 'No ERP data loaded.'}
              </span>
            </CardDescription>
          </div>
          <div className="ml-auto flex items-center gap-2">
             <input
              type="file"
              ref={erpFileInputRef}
              onChange={handleErpCSVUpload}
              accept=".csv"
              className="hidden"
            />
            <Button size="sm" variant="outline" className="h-8 gap-1" onClick={handleErpImportClick}>
              <Database className="h-3.5 w-3.5" />
              <span className="sr-only sm:not-sr-only sm:whitespace-nowrap">
                Import ERP Data
              </span>
            </Button>
            <input
              type="file"
              ref={fileInputRef}
              onChange={handleCSVUpload}
              accept=".csv"
              className="hidden"
            />
            <Button size="sm" variant="outline" className="h-8 gap-1" onClick={handleImportClick}>
              <Upload className="h-3.5 w-3.5" />
              <span className="sr-only sm:not-sr-only sm:whitespace-nowrap">
                Import Products
              </span>
            </Button>
            <Button size="sm" variant="outline" className="h-8 gap-1" onClick={handleExportToCSV}>
              <File className="h-3.5 w-3.5" />
              <span className="sr-only sm:not-sr-only sm:whitespace-nowrap">
                Export
              </span>
            </Button>
             <Dialog open={isBulkEditOpen} onOpenChange={setIsBulkEditOpen}>
              <DialogTrigger asChild>
                  <Button size="sm" variant="outline" className="h-8 gap-1" disabled={selectedProductIds.length === 0}>
                    <FilePenLine className="h-3.5 w-3.5" />
                    <span className="sr-only sm:not-sr-only sm:whitespace-nowrap">
                        Bulk Edit ({selectedProductIds.length})
                    </span>
                  </Button>
              </DialogTrigger>
              <DialogContent className="sm:max-w-md">
                <DialogHeader>
                    <DialogTitle>Bulk Edit Products</DialogTitle>
                    <DialogDescription>
                        Modify the fields below to update all {selectedProductIds.length} selected products at once.
                    </DialogDescription>
                </DialogHeader>
                <BulkEditForm 
                    onSave={handleSaveBulkEdit} 
                    onCancel={() => setIsBulkEditOpen(false)}
                />
              </DialogContent>
            </Dialog>
            <Sheet open={isSheetOpen} onOpenChange={setIsSheetOpen}>
              <SheetTrigger asChild>
                  <Button size="sm" className="h-8 gap-1" onClick={handleAddProduct}>
                  <PlusCircle className="h-3.5 w-3.5" />
                  <span className="sr-only sm:not-sr-only sm:whitespace-rap">
                    Add Product
                  </span>
                </Button>
              </SheetTrigger>
              <SheetContent className="sm:max-w-2xl" side="right">
                <SheetHeader>
                    <SheetTitle>{selectedProduct ? 'Edit Product' : 'Add New Product'}</SheetTitle>
                  <SheetDescription>
                    {selectedProduct
                      ? 'Update the details of your product.'
                      : 'Fill in the details for the new product.'}
                  </SheetDescription>
                </SheetHeader>
                <ProductForm 
                  product={selectedProduct} 
                  onSave={handleSaveProduct} 
                  onCancel={() => setIsSheetOpen(false)} 
                />
              </SheetContent>
            </Sheet>
          </div>
        </CardHeader>
        <CardContent>
          <ProductDataTable 
            columns={columns} 
            data={products} 
            onSelectionChange={setSelectedProductIds}
            onBulkDelete={handleBulkDelete}
          />
        </CardContent>
      </Card>
    </main>
  );
}

export default function Dashboard() {
    return (
        <ErpDataProvider>
            <DashboardClient />
        </ErpDataProvider>
    );
}
