// This file is generated by Firebase Studio
import { initializeApp, getApps } from 'firebase/app';
import { getAuth, connectAuthEmulator } from 'firebase/auth';

// This is the primary configuration object for the Firebase client SDK.
// It is read from environment variables, which are set during the build process.
const firebaseConfig = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
};


// Function to initialize and get the Firebase app instance.
// It ensures that Firebase is initialized only once.
const getFirebaseApp = () => {
  const apps = getApps();
  if (apps.length > 0) {
    return apps[0];
  }
  
  // Before initializing, we verify that all the required configuration keys are present.
  // This is a safeguard against runtime errors due to a missing .env configuration.
  if (!firebaseConfig.apiKey || !firebaseConfig.projectId) {
    console.error(
      '[AUTH DBG] Firebase config is missing or incomplete. Check your environment variables.',
      {
        apiKey: !!firebaseConfig.apiKey,
        authDomain: !!firebaseConfig.authDomain,
        projectId: !!firebaseConfig.projectId,
      }
    );
    // Throwing an error is important here to prevent the app from continuing
    // in a broken state.
    throw new Error('Firebase config is missing or incomplete. Please check your environment variables.');
  }

  return initializeApp(firebaseConfig);
};


// Initialize the Firebase app instance.
export const app = getFirebaseApp();

// Get the Firebase Auth instance.
export const auth = getAuth(app);

// If we are in a local development environment (and not in a test environment like Jest),
// we connect the Auth emulator to allow for local testing without real credentials.
// The `process.env.NODE_ENV` variable is set automatically by Next.js.
if (process.env.NODE_ENV === 'development') {
  try {
    // Note: The host for the emulator must include the protocol (http://).
    // The default port for the Firebase Auth emulator is 9099.
    connectAuthEmulator(auth, 'http://127.0.0.1:9099', { disableWarnings: true });
    console.log('[AUTH DBG] Firebase Auth Emulator connected.');
  } catch (e) {
    // If the emulator is not running, we log a warning but do not stop the app.
    // This allows developers to work on other parts of the app without needing
    // to run the Firebase emulator suite.
    console.warn(
      '[AUTH DBG] Could not connect to Firebase Auth Emulator. Make sure it is running. Error:',
      e
    );
  }
}
