// This file is generated by Firebase Studio
import { initializeApp, getApps, getApp, type FirebaseApp } from 'firebase/app';
import { getAuth, type Auth } from 'firebase/auth';
import { getFirestore, type Firestore } from 'firebase/firestore';

// Hardcoded config to debug environment variable issues
const firebaseConfig = {
  apiKey: "AIzaSyBnLCLDNhL64QG6kagfwSAXyCOdB-H7ENA",
  authDomain: "listingflow-sp4tf.firebaseapp.com",
  projectId: "listingflow-sp4tf",
  storageBucket: "listingflow-sp4tf.appspot.com",
  messagingSenderId: "935922706940",
  appId: "1:935922706940:web:2fc04bfc3e3240cfc82a79",
};

// Log the config to be sure it's correct
console.log('[AUTH DBG CONFIG]', firebaseConfig);

// Initialize Firebase
const app: FirebaseApp = getApps().length ? getApp() : initializeApp(firebaseConfig);
const auth: Auth = getAuth(app);
const db: Firestore = getFirestore(app);

export { app, auth, db };