// This file is generated by Firebase Studio
'use client';

import * as React from 'react';
import AppShell from '@/components/app-shell';
<<<<<<< HEAD
import { useAuth } from '@/contexts/auth-context';
import { Loader2 } from 'lucide-react';

export default function ProtectedLayout({ children }: { children: React.ReactNode }) {
  const { user, loading } = useAuth();

  // If loading, or if not loading and no user, show loading screen.
  // The redirect logic is handled centrally in AuthProvider.
  if (loading || !user) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <Loader2 className="h-8 w-8 animate-spin" />
      </div>
    );
  }
=======
>>>>>>> 134e3595c39a3a6bfdd1abc89abe26cb0e48483d

export default function ProtectedLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <AppShell>{children}</AppShell>;
}
