// This file is generated by Firebase Studio

import { NextResponse } from 'next/server';

export async function POST(req: Request) {
  try {
    const { endpoint, method = 'GET', body } = await req.json();

    const url = process.env.ERPNEXT_URL;
    const apiKey = process.env.ERPNEXT_API_KEY;
    const apiSecret = process.env.ERPNEXT_API_SECRET;
    
    if (!url || !apiKey || !apiSecret) {
        return NextResponse.json(
            { error: 'ERPNext credentials are not configured in the environment variables.' },
            { status: 500 }
        );
    }

    const fullUrl = `${url.replace(/\/$/, '')}${endpoint}`;

    const headers: Record<string, string> = {
      'Authorization': `token ${apiKey}:${apiSecret}`,
      'Content-Type': 'application/json',
      'Accept': 'application/json',
    };

    const requestOptions: RequestInit = {
      method,
      headers,
      body: body ? JSON.stringify(body) : undefined,
      cache: 'no-store', // Ensure fresh data is fetched
    };
    
    const response = await fetch(fullUrl, requestOptions);

    if (!response.ok) {
        let errorDetails = '';
        try {
            const errorBody = await response.json();
            errorDetails = errorBody.message || errorBody.exception || errorBody.error || JSON.stringify(errorBody);
        } catch {
            errorDetails = await response.text();
        }
        return NextResponse.json({ error: `${response.status} - ${errorDetails}` }, { status: response.status });
    }

    // Handle no content response
    if (response.status === 204) {
      return new NextResponse(null, { status: 204 });
    }

    const data = await response.json();
    return NextResponse.json(data);

  } catch (err: any) {
    console.error("API Proxy Error:", err);
    return NextResponse.json(
      { error: err.message || 'An unexpected error occurred in the API proxy.' },
      { status: 500 }
    );
  }
}

// Handle OPTIONS requests for CORS preflight
export async function OPTIONS() {
  return new NextResponse(null, {
    status: 204,
    headers: {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'POST, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type, Authorization',
    },
  });
}
