// This file is generated by Firebase Studio
'use client';

import * as React from 'react';
import { Button } from '@/components/ui/button';
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { useToast } from '@/hooks/use-toast';
import { Trash2 } from 'lucide-react';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog"

function SettingsClient() {
  const { toast } = useToast();
   const [erpNextUrl, setErpNextUrl] = React.useState('');

  React.useEffect(() => {
    // The actual usage is server-side or at build time.
    // To make it available client-side for display, we prefix it with NEXT_PUBLIC_
    const url = process.env.NEXT_PUBLIC_ERPNEXT_BASE_URL;
    setErpNextUrl(url || 'Not set in environment variables');
  }, []);

  const handleClearData = () => {
    localStorage.removeItem('listingFlowProducts');
    // Note: This does not clear .env variables as they are server-side.
    // Advise user to clear them manually if needed.
    toast({
      title: 'Local Data Cleared',
      description: 'Your local product data has been successfully deleted from the browser. Your API credentials in the .env file are not affected.',
    });
     setTimeout(() => window.location.href = '/', 1000);
  };

  return (
    <div className="grid gap-6">
       <Card>
        <CardHeader>
          <CardTitle>ERPNext Integration</CardTitle>
          <CardDescription>
            Your ERPNext credentials should be stored securely. The method depends on your environment.
            <br /><br />
            <strong>For Local Development (Test Mode):</strong>
            <p className="mb-2">
              Create a file named <strong>.env.local</strong> in the root of your project and add your test credentials there. This file is ignored by version control and will not be published.
            </p>
             <pre className="mt-2 p-2 bg-muted rounded-md text-sm font-mono">
{`# .env.local (for testing)
ERPNEXT_BASE_URL="https://your-test-erp.rembayer.info"
NEXT_PUBLIC_ERPNEXT_BASE_URL="https://your-test-erp.rembayer.info"
ERPNEXT_API_KEY="your_test_api_key"
ERPNEXT_API_SECRET="your_test_api_secret"
NEXT_PUBLIC_ENV="dev"`}
            </pre>
            <br />
            <strong>For Production (after publishing):</strong>
             <p className="mb-2">
              In your hosting environment (like Firebase App Hosting), you must set these as secrets. The application is configured to read them from `apphosting.yaml`.
            </p>
             <pre className="mt-2 p-2 bg-muted rounded-md text-sm font-mono">
{`# For production (set in hosting provider)
ERPNEXT_BASE_URL="https://your-prod-erp.rembayer.info"
NEXT_PUBLIC_ERPNEXT_BASE_URL="https://your-prod-erp.rembayer.info"
# ERPNEXT_API_KEY and ERPNEXT_API_SECRET should be secrets
NEXT_PUBLIC_ENV="prod"
`}
            </pre>
             <p className="mt-4 text-sm text-muted-foreground">
              The app will construct image URLs using the public base URL: <strong>{erpNextUrl}</strong>
            </p>
          </CardDescription>
        </CardHeader>
      </Card>
      
      <Card>
        <CardHeader>
          <CardTitle>Settings</CardTitle>
          <CardDescription>
            Manage your application settings and preferences.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-6">
            <div>
              <h3 className="text-lg font-medium">Appearance</h3>
              <p className="text-sm text-muted-foreground">
                This setting is now controlled from the user menu in the header.
              </p>
            </div>
          </div>
        </CardContent>
      </Card>

      <Card className="border-destructive">
          <CardHeader>
              <CardTitle>Danger Zone</CardTitle>
              <CardDescription>These actions are permanent and cannot be undone.</CardDescription>
          </CardHeader>
          <CardContent>
              <AlertDialog>
                  <AlertDialogTrigger asChild>
                      <Button variant="destructive">
                          <Trash2 className="mr-2 h-4 w-4" />
                          Clear All Local Product Data
                      </Button>
                  </AlertDialogTrigger>
                  <AlertDialogContent>
                      <AlertDialogHeader>
                      <AlertDialogTitle>Are you absolutely sure?</AlertDialogTitle>
                      <AlertDialogDescription>
                          This action cannot be undone. This will permanently delete all your product data
                          from your browser's local storage. Your API credentials in .env will not be affected.
                      </AlertDialogDescription>
                      </AlertDialogHeader>
                      <AlertDialogFooter>
                      <AlertDialogCancel>Cancel</AlertDialogCancel>
                      <AlertDialogAction onClick={handleClearData}>Continue</AlertDialogAction>
                      </AlertDialogFooter>
                  </AlertDialogContent>
              </AlertDialog>
          </CardContent>
      </Card>
    </div>
  )
}

export default function SettingsPage() {
  return (
    <main className="grid flex-1 items-start gap-4 p-4 sm:px-6 sm:py-0 md:gap-8">
      <SettingsClient />
    </main>
  );
}
